// 文件功能：周报接口 Mock 数据集合，处于本地调试阶段
// 方法概览：提供不同 feedling 状态的 mock 报告
import type { WeeklyReportApiResponse } from "@/domain/report/types";

// 方法功能：mock 报告数据映射
export const mockReports: Record<string, WeeklyReportApiResponse> = {
  curious: {
    id: 101,
    app_user_id: "preview-curious",
    email_content: null,
    period_start: "2026-01-18T00:00:00Z",
    period_end: "2026-01-24T23:59:59Z",
    created_at: "2026-01-25T03:20:00Z",
    updated_at: "2026-01-25T03:20:00Z",
    send_status: "pending",
    feeding_state: "curious",
    trend_name: "Leave Em Alone",
    trend_type: "sound",
    discovery_rank: 47,
    total_discoverers: 2847,
    origin_niche_text: "#BeautyTik",
    spread_end_text: "going_mainstream",
    reach_start: 0.2,
    reach_end: 8,
    current_reach: 0.2,
    total_videos: 9222,
    total_time: 1154,
    pre_total_time: 1290,
    miles_scrolled: 18,
    topics: [
      { topic: "Travel", pic_url: "https://picsum.photos/200/200?1" },
      { topic: "Crafts", pic_url: "https://picsum.photos/200/200?2" },
      { topic: "Music", pic_url: "https://picsum.photos/200/200?3" },
    ],
    timezone: "America/Los_Angeles",
    rabbit_hole_datetime: null,
    rabbit_hole_date: "Wednesday",
    rabbit_hole_time: "3:09 AM",
    rabbit_hole_count: 38,
    rabbit_hole_category: "Comedy",
    nudge_text: "Your Feedling had a balanced week. Keep it up!",
  },
  excited: {
    id: 102,
    app_user_id: "preview-excited",
    email_content: null,
    period_start: "2026-01-18T00:00:00Z",
    period_end: "2026-01-24T23:59:59Z",
    created_at: "2026-01-25T03:20:00Z",
    updated_at: "2026-01-25T03:20:00Z",
    send_status: "pending",
    feeding_state: "excited",
    trend_name: "Leave Em Alone",
    trend_type: "hashtag",
    discovery_rank: 18,
    total_discoverers: 2847,
    origin_niche_text: "#BeautyTik",
    spread_end_text: "spreading",
    reach_start: 0.2,
    reach_end: 4,
    current_reach: 3.2,
    total_videos: 6100,
    total_time: 980,
    pre_total_time: 900,
    miles_scrolled: 12,
    topics: [
      { topic: "Music", pic_url: "https://picsum.photos/200/200?4" },
      { topic: "Fitness", pic_url: "https://picsum.photos/200/200?5" },
    ],
    timezone: "America/Los_Angeles",
    rabbit_hole_datetime: null,
    rabbit_hole_date: "Monday",
    rabbit_hole_time: "11:20 PM",
    rabbit_hole_count: 24,
    rabbit_hole_category: "Music",
    nudge_text: "Try setting a scroll limit for yourself",
  },
  sleepy: {
    id: 103,
    app_user_id: "preview-sleepy",
    email_content: null,
    period_start: "2026-01-18T00:00:00Z",
    period_end: "2026-01-24T23:59:59Z",
    created_at: "2026-01-25T03:20:00Z",
    updated_at: "2026-01-25T03:20:00Z",
    send_status: "pending",
    feeding_state: "sleepy",
    trend_name: "Silent Loop",
    trend_type: "creator",
    discovery_rank: null,
    total_discoverers: 4021,
    origin_niche_text: "#ArtTok",
    spread_end_text: "almost_everywhere",
    reach_start: 0.2,
    reach_end: 10,
    current_reach: 9.1,
    total_videos: 11880,
    total_time: 1500,
    pre_total_time: 1320,
    miles_scrolled: 32,
    topics: [{ topic: "Food", pic_url: "https://picsum.photos/200/200?6" }],
    timezone: "America/Los_Angeles",
    rabbit_hole_datetime: "2026-01-21T10:34:00Z",
    rabbit_hole_date: "Saturday",
    rabbit_hole_time: "2:34 AM",
    rabbit_hole_count: 160,
    rabbit_hole_category: "Comedy",
    nudge_text: "Try putting your phone down before 2 AM this week",
  },
  dizzy: {
    id: 104,
    app_user_id: "preview-dizzy",
    email_content: null,
    period_start: "2026-01-18T00:00:00Z",
    period_end: "2026-01-24T23:59:59Z",
    created_at: "2026-01-25T03:20:00Z",
    updated_at: "2026-01-25T03:20:00Z",
    send_status: "pending",
    feeding_state: "dizzy",
    trend_name: "Glow Up",
    trend_type: "format",
    discovery_rank: 980,
    total_discoverers: 2847,
    origin_niche_text: "#GlowTok",
    spread_end_text: "everywhere",
    reach_start: 0.2,
    reach_end: 12,
    current_reach: 11.6,
    total_videos: 10400,
    total_time: 1420,
    pre_total_time: 1100,
    miles_scrolled: 20,
    topics: [
      { topic: "Fashion", pic_url: "https://picsum.photos/200/200?7" },
      { topic: "Gaming", pic_url: "https://picsum.photos/200/200?8" },
    ],
    timezone: "America/Los_Angeles",
    rabbit_hole_datetime: "2026-01-23T09:45:00Z",
    rabbit_hole_date: "Friday",
    rabbit_hole_time: "1:45 AM",
    rabbit_hole_count: 88,
    rabbit_hole_category: "Meme",
    nudge_text: "Try using 'Not Interested' on a few videos this week",
  },
  cozy: {
    id: 105,
    app_user_id: "preview-cozy",
    email_content: null,
    period_start: "2026-01-18T00:00:00Z",
    period_end: "2026-01-24T23:59:59Z",
    created_at: "2026-01-25T03:20:00Z",
    updated_at: "2026-01-25T03:20:00Z",
    send_status: "pending",
    feeding_state: "cozy",
    trend_name: "Calm Desk Setup",
    trend_type: "sound",
    discovery_rank: 320,
    total_discoverers: 2847,
    origin_niche_text: "#WorkTok",
    spread_end_text: "going_mainstream",
    reach_start: 0.2,
    reach_end: 8,
    current_reach: 7.1,
    total_videos: 7800,
    total_time: 990,
    pre_total_time: 1140,
    miles_scrolled: 14,
    topics: [
      { topic: "Crafts", pic_url: "https://picsum.photos/200/200?9" },
      { topic: "Fitness", pic_url: "https://picsum.photos/200/200?10" },
    ],
    timezone: "America/Los_Angeles",
    rabbit_hole_datetime: null,
    rabbit_hole_date: "Thursday",
    rabbit_hole_time: "10:15 PM",
    rabbit_hole_count: 40,
    rabbit_hole_category: "Lifestyle",
    nudge_text: "Your Feedling had a balanced week. Keep it up!",
  },
};
