// 文件功能：应用根布局与基础元信息，处于 Next App 的入口层
// 方法概览：根布局组件
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

// 方法功能：提供全局 HTML 与 body 容器
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
