/**
 * Satori Renderer Module
 * (Satori 渲染器模块)
 *
 * Responsible for converting React components (Satori templates) into PNG images.
 * This module handles the "Assets" generation phase of the pipeline.
 * (负责将 React 组件（Satori 模板）转换为 PNG 图片。该模块处理流水线的“资源”生成阶段。)
 *
 * Supported Renderers (支持的渲染器):
 * - Trend Progress Bar (趋势进度条)
 * - Diagnosis Bar Chart (诊断柱状图)
 * - Trend Share Card (趋势分享卡片)
 * - Stats Share Card (统计分享卡片)
 */
import satori from "satori";
import { Resvg } from "@resvg/resvg-js";
import { TrendProgress } from "@/components/satori/TrendProgress";
import { DiagnosisBarChart } from "@/components/satori/DiagnosisBarChart";
import { TrendShareCard } from "@/components/satori/TrendShareCard";
import { StatsShareCard } from "@/components/satori/StatsShareCard";
import type { TrendType } from "@/domain/report/types";
import { fetchImageData, loadFontData, loadImageData } from "./image-loader";

const RENDER_SCALE = 2;
const FONT_NAME = "Noto Sans";

/**
 * Resolves the appropriate icon filename based on the trend type.
 * (根据趋势类型解析相应的图标文件名。)
 *
 * @param trendType - The category of the trend (sound, hashtag, etc.) (趋势类别，如 sound, hashtag 等)
 * @returns Filename of the icon (图标的文件名)
 */
function getTrendIconFileName(trendType?: TrendType) {
  if (trendType === "sound") return "trend-icon_sound.png";
  if (trendType === "hashtag") return "trend-icon_hashtag.png";
  if (trendType === "creator") return "trend-icon_creator.png";
  if (trendType === "format") return "trend-icon_format.png";
  return "trend-icon.png";
}

/**
 * Converts a raw SVG string into a PNG Buffer.
 * Uses `resvg-js` for high-quality rendering.
 * (将原始 SVG 字符串转换为 PNG Buffer。使用 `resvg-js` 进行高质量渲染。)
 *
 * @param svg - The SVG string generated by Satori (由 Satori 生成的 SVG 字符串)
 * @returns PNG Buffer (PNG 缓冲区)
 */
function renderSvgToPng(svg: string) {
  // Use high-resolution scaling for clear images in emails and retina displays
  const resvg = new Resvg(svg, {
    fitTo: { mode: "zoom", value: RENDER_SCALE },
  });
  const pngData = resvg.render();
  return Buffer.from(pngData.asPng());
}

/**
 * Renders the Trend Progress bar as a PNG.
 * Used in the email body visual.
 *
 * @param options - Configuration for progress and dimensions
 */
export async function renderTrendProgressImage(options: {
  progress: number;
  width?: number;
  height?: number;
}) {
  const baseWidth = options.width ?? 520;
  const baseHeight = options.height ?? 64;
  const horizontalPadding = 23;
  const width = baseWidth + horizontalPadding * 2;
  const height = baseHeight;

  // Load necessary fonts and assets
  const fontData = await loadFontData();
  const fireIconData = await loadImageData("fire.png");

  // Generate SVG via Satori
  const svg = await satori(
    <div
      style={{
        width,
        height,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
      }}
    >
      <div style={{ width: baseWidth, height: baseHeight, display: "flex" }}>
        <TrendProgress
          progress={options.progress}
          fireIconData={fireIconData}
          width={baseWidth}
        />
      </div>
    </div>,
    {
      width,
      height,
      fonts: [
        {
          name: FONT_NAME,
          data: fontData.regular,
          weight: 400,
          style: "normal",
        },
        { name: FONT_NAME, data: fontData.bold, weight: 700, style: "normal" },
      ],
    },
  );

  return renderSvgToPng(svg);
}

/**
 * Renders the Diagnosis Bar Chart as a PNG.
 * Used in the "Stats" section of the email.
 *
 * @param options - Data points and labels for the chart
 */
export async function renderDiagnosisBarChartImage(options: {
  lastWeekLabel: string;
  thisWeekLabel: string;
  lastWeekValue: number;
  thisWeekValue: number;
  width?: number;
  height?: number;
}) {
  const width = options.width ?? 520;
  const height = options.height ?? 265;

  // Ensure consistent font rendering
  const fontData = await loadFontData();

  // Generate SVG via Satori
  const svg = await satori(
    <DiagnosisBarChart
      lastWeekLabel={options.lastWeekLabel}
      thisWeekLabel={options.thisWeekLabel}
      lastWeekValue={options.lastWeekValue}
      thisWeekValue={options.thisWeekValue}
    />,
    {
      width,
      height,
      fonts: [
        {
          name: FONT_NAME,
          data: fontData.regular,
          weight: 400,
          style: "normal",
        },
        { name: FONT_NAME, data: fontData.bold, weight: 700, style: "normal" },
      ],
    },
  );

  return renderSvgToPng(svg);
}

/**
 * Renders the Trend Share Card as a PNG.
 * Used for social sharing and download.
 *
 * @param options - Full content and data for the trend card
 */
export async function renderTrendShareCardImage(options: {
  topicTitle: string;
  topicSubtitle: string;
  discoveryRank: number;
  totalDiscovery: string;
  progress: number;
  hashtag: string;
  hashtagPercent: string;
  endTag: string;
  globalPercent: string;
  width?: number;
  height?: number;
  trendType?: TrendType;
  topicIconData?: string;
  topicIconBgData?: string;
  topBgData?: string;
  bottomBgData?: string;
}) {
  const width = options.width ?? 600;
  const height = options.height ?? 1000;

  const fontData = await loadFontData();

  // Parallel asset loading for performance
  const [
    defaultTopicIconData,
    defaultTopicIconBgData,
    fireIconData,
    defaultTopBgData,
    defaultBottomBgData,
  ] = await Promise.all([
    loadImageData(getTrendIconFileName(options.trendType)),
    loadImageData("trend-icon-bg.png"),
    loadImageData("fire.png"),
    loadImageData("trend-card-bg_top.png"),
    loadImageData("trend-card-bg_bottom.png"),
  ]);

  const topicIconData = options.topicIconData ?? defaultTopicIconData;
  const topicIconBgData = options.topicIconBgData ?? defaultTopicIconBgData;
  const topBgData = options.topBgData ?? defaultTopBgData;
  const bottomBgData = options.bottomBgData ?? defaultBottomBgData;

  // Compose the card component and render to SVG
  const svg = await satori(
    <TrendShareCard
      topicIconData={topicIconData}
      topicIconBgData={topicIconBgData}
      topicTitle={options.topicTitle}
      topicSubtitle={options.topicSubtitle}
      discoveryRank={options.discoveryRank}
      totalDiscovery={options.totalDiscovery}
      progress={options.progress}
      fireIconData={fireIconData}
      hashtag={options.hashtag}
      hashtagPercent={options.hashtagPercent}
      endTag={options.endTag}
      globalPercent={options.globalPercent}
      topBgData={topBgData}
      bottomBgData={bottomBgData}
    />,
    {
      width,
      height,
      fonts: [
        {
          name: FONT_NAME,
          data: fontData.regular,
          weight: 400,
          style: "normal",
        },
        { name: FONT_NAME, data: fontData.bold, weight: 700, style: "normal" },
        { name: FONT_NAME, data: fontData.bold, weight: 900, style: "normal" },
      ],
    },
  );

  return renderSvgToPng(svg);
}

/**
 * Renders the Stats Share Card as a PNG.
 * Used for social sharing and download.
 *
 * @param options - Full content and data for the stats card
 */
export async function renderStatsShareCardImage(options: {
  totalVideos: string;
  totalTime: string;
  miles: string;
  comparisonDiff?: string | null;
  comparisonText: string;
  milesComment?: string;
  barChartData: {
    lastWeekLabel: string;
    thisWeekLabel: string;
    lastWeekValue: number;
    thisWeekValue: number;
  };
  width?: number;
  height?: number;
  contents: {
    label: string;
    iconUrl: string;
  }[];
}) {
  const width = options.width ?? 600;
  const height = options.height ?? 1000;

  const fontData = await loadFontData();

  // Parallel asset loading
  const [headerIconData, topBgData, bottomBgData] = await Promise.all([
    loadImageData("stats-icon.png"),
    loadImageData("stats-card-bg_top.png"),
    loadImageData("stats-card-bg_bottom.png"),
  ]);

  // Convert remote icon URLs to base64 for Satori
  const contents = await Promise.all(
    options.contents.slice(0, 3).map(async (content) => ({
      label: content.label,
      icon: await fetchImageData(content.iconUrl),
    })),
  );

  // Compose the card component and render to SVG
  const svg = await satori(
    <StatsShareCard
      headerIconData={headerIconData}
      totalVideos={options.totalVideos}
      totalTime={options.totalTime}
      miles={options.miles}
      comparisonDiff={options.comparisonDiff}
      comparisonText={options.comparisonText}
      milesComment={options.milesComment}
      barChartData={options.barChartData}
      contents={contents}
      topBgData={topBgData}
      bottomBgData={bottomBgData}
    />,
    {
      width,
      height,
      fonts: [
        {
          name: FONT_NAME,
          data: fontData.regular,
          weight: 400,
          style: "normal",
        },
        { name: FONT_NAME, data: fontData.bold, weight: 700, style: "normal" },
      ],
    },
  );

  return renderSvgToPng(svg);
}
